# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 2, 52, 38, 912832, tzinfo=utc), verbose_name=b'Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.TextField(verbose_name=b'Cookie'),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='domain',
            field=models.CharField(max_length=256, verbose_name=b'Domain'),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='ip',
            field=models.CharField(max_length=256, verbose_name=b'IP'),
        ),
    ]
