# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0002_auto_20160802_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'Update Time'),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Time'),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='domain',
            field=models.CharField(max_length=256, verbose_name=b'From'),
        ),
    ]
