# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0003_auto_20160802_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='update',
        ),
    ]
